---
title: "CV"
output: 
  html_document:
   # css: bootstrap.css
    toc: true
    toc_float: true
---
## EXPERIENCE
Columbia University, Mailman School of Public Health	NY, NY
Senior Data Analyst, Department of Epidemiology	        April 2019 – Present
•	Project manage agent-based modeling (ABM) component of Columbia University’s NIH HEAL (Helping to End Addiction Long-term) grant
•	Build ABM from the ground-up of opioid related outcomes, representing 16 counties in NY State
•	Organize and lead meetings with project stakeholders to discuss progress of ABM components

Senior Data Analyst, Department of Epidemiology	March 2018 – March 2019
Data Analyst, Department of Epidemiology	Dec 2012 – February 2018
•	Agent-based modeling in Java; aggregate national and local data to parameterize and calibrate models to be representative of the New York City Population
•	Data analysis in SAS and R including statistical testing, multi-level logistic and linear regressions, and age-period-cohort analyses on large-scale data
•	Supervise and mentor data analysts, masters, and doctoral students on large-scale projects, and advise how to use unique statistical techniques on cross-sectional and longitudinal national survey 
•	Lead and assist on manuscript and grant composition and preparation 
•	Annually present research findings at national conferences 
•	Created representative weights for brain scan datasets: PING, Healthy Brain Network, NKI /Rockland Sample
•	Columbia University Data Manager for Detroit based DNHS data and Europe based SCMHE data and facilitate data sharing

Department of Health and Mental Hygiene	Queens, NY
Epidemiology Intern	January 2012
•	Used ArcGIS to create maps of psychiatric hospitalization rates in NYC

Skidmore College	Saratoga Springs, New York
Primary Data Analyst, Mathematics Department	June 2010 – January 2011
•	Wrote algorithms in MATLAB to fit a curve to a set of data points and optimize this curve
•	Tested effectiveness of MATLAB algorithms by creating and implementing fake data
•	Presented findings and won award at Joint Mathematics Meeting, 2011

Math Tutor, Mathematics Department	January 2010 – May 2012
•	Ran review sessions, and tutored students in calculus I/II and pre-calculus

## EDUCATION
Skidmore College	Saratoga Springs, New York
Bachelor of Arts with honors in Mathematics, 3.79 / 4.0	May 2012
•	Relevant Coursework: Artificial Intelligence, Numerical Algorithms, Probability and Statistics, Differential Equations, Discrete Mathematics, Linear Algebra
•	Relevant Project: Used Java to create a board game, an alpha-beta player, and a reinforcement learner player.
•	Honors Thesis: Symmetry in Knitting: Applying mathematical concepts through knitting

Columbia University, School of Engineering and Applied Science	New York, NY
Graduate Level Coursework	Fall 2014
•	Database Systems course project: Created a database of a simplified MTA Subway System, to interface with an app in which a user could input starting and ending locations, and directions would be returned

## SELECTED HONORS AND AWARDS
Phi Beta Kappa, 2012
Gladys Gillman Taylor Prize in Mathematics, 2012 
Pi Mu Epsilon - honorary national mathematics society, 2011
American Mathematical Society Mathematics Department Award, 2011 
Joint Mathematics Meeting Student Poster Session Award, 2011
Schupf Scholar – Scholarship for scientific research, 2010
Mathematics Association of America Mathematics Department Award, 2010 
	
## PUBLICATIONS
### Peer Reviewed Journal Publications
•	Hatzenbuehler ML, Keyes KM, Hamilton A, Hasin DS. (2014). State-Level Tobacco Environments and Sexual Orientation Disparities in Tobacco Use and Dependence in the United States. Tobacco Control, ePub Feb 25 2014. PMID: 24570099; PMCID: PMC4386615.
•	Barnes D, Keyes KM, Hamilton A, Hatzenbuehler ML. (2014). Sexual orientation disparities in mental health: the moderating role of educational attainment. Social Psychiatry and Psychiatric Epidemiology, ePub Feb 26 2014. PMID: 24570204; PMCID: PMC4145056.
•	Keyes KM, Susser E, Pilowsky DJ, Hamilton A, Bitfoi A, Goelitz D, Kuijpers RC, Lesinskiene S, Mihova Z, Otten R, Kovess V. The health consequences of child mental health problems and parenting styles: unintentional injuries among European schoolchildren. Preventive Med. ePub Jul 26 2014. PMID: 25073079; PMCID: PMC4409127. 
•	Kovess V, Keyes KM, Hamilton A, Pez O, Bitfoi A, Koç C, Goelitz D, Kuijpers R, Lesinskiene S, Mihova Z, Otten R, Fermanian C, Pilowsky DJ, Susser E. Maternal smoking and offspring inattention and hyperactivity: results from a cross-national European survey. European Child & Adolescent Psychiatry. ePub Nov 21 2014. PMID: 25413602; PMCID: PMC4440844.
•	Hatzenbuehler ML, Keyes K, Hamilton A, Uddin M, Galea S. The Collateral Damage of Mass Incarceration: Risk of Psychiatric Morbidity Among Nonincarcerated Residents of High-Incarceration Neighborhoods. American Journal Public Health. Jan 2015. PMID: 25393200; PMCID: PMC4265900.
•	Keyes KM, Maslowsky J, Hamilton A, Schulenberg J. The great sleep recession: changes in sleep duration among US adolescents, 1991-2012. Pediatrics. Mar 2015. PMID: 25687142; PMCID: PMC4338325.
•	Ananth CV, Keyes KM, Hamilton A, Gissler M, Wu C, Liu S, Luque-Fernandez MA, Skjærven R, Williams MA, Tikkanen M, Cnattingius S. An international contrast of rates of placental abruption: an age-period-cohort analysis. PLoS One. May 27 2015. PMID: 26018653; PMCID: PMC4446321. 
•	Keyes KM, Jager J, Hamilton A, O'Malley PM, Miech R, Schulenberg JE. National multi-cohort time trends in adolescent risk preference and the relation with substance use and problem behavior from 1976 to 2011. Drug and Alcohol Dependence. ePub Jul 2 2015. PMID: 26254018; PMCID: PMC4581913.
•	Keyes K, Agnew-Blais J, Roberts AL, Hamilton A, De Vivo I, Ranu H, Koenen K. The role of allelic variation in estrogen receptor genes and major depression in the Nurses Health Study. Social Psychiatry and Psychiatric Epidemiology. ePub Jul 14 2015. PMID: 26169989; PMCID: PMC4655148.
•	Kovess V, Keyes KM, Hamilton A, Hanson G, Bitfoi A, Golitz D, Koc C, Kuijpers R, Lesinskiene S, Mihova Z, Otten R, Fermanian C, Pez O. 2016. Are video games promoting or deteriorating mental health, cognitive and social skills in young children? Social Psychiatry and Psychiatric Epidemiology, ePub Feb 5. PMID: 26846228; PMCID: PMC4814321.
•	Keyes K, Hamilton A, Kandel D. Birth Cohorts Analysis of Adolescent Cigarette Smoking and Subsequent Marijuana and Cocaine Use. American Journal of Public Health: June 2016, Vol. 106, No. 6, pp. 1143-1149. PMID: 27077359. 
•	Kovess-Masfety V, Husky MM, Keyes KM, Hamilton A, Pez O, Bitfoi A, Carta MG, Goelitz D, Kuijpers R, Otten R, Koc C, Lesinskiene S, Mihova Z. Comparing the prevalence of mental health problems in children 6-11 across Europe. Social Psychiatry and Psychiatric Epidemiology: Sept 2016. PMID: 27314494.
•	Keyes KM, Rutherford C, Hamilton A, Palamar JJ. Age, period, and cohort effects in synthetic cannabinoid use among US adolescents, 2011-2015. Drug and Alcohol Dependence: Sept 2016. PMID: 27491817. 
•	Jang JB, Patrick ME, Keyes KM, Hamilton A, Schulenberg JE. Frequent Binge Drinking Among US Adolescents, 1991 to 2015. Pediatrics: June 2017. PMID: 28562275.
•	Ananth CV, Friedman AM, Keyes KM, Lavery JA, Hamilton A, Wright J. Primary and Repeat Cesarean Deliveries: A Population-based Study in the United States, 1979–2010. Epidemiology: July 2017. PMID: 28346271.
•	Husky MM, Keyes K, Hamilton A, Stragalinou A, Pez O, Kuijpers R, Lesinskiene S, Mihova Z, Otten R, Kovess-Masfety V. Maternal Problem Drinking and Child Mental Health. Substance Use & Misuse: July 2017. PMID: 28704164.
•	Walsh K, McLaughlin KA, Hamilton A, Keyes KM. Trauma exposure, incident psychiatric disorders, and disorder transitions in a longitudinal population representative sample. Journal of Psychiatric Research: Sept 2017. PMID: 28531836.
•	LeWinn KZ, Sheridan MA, Keyes KM, Hamilton A, McLaughlin K. Sample composition alters associations between age and brain structure. Nature Communications. ePub Oct 12 2017. 
•	Keyes KM, Gary D, O'Malley P, Hamilton A, Schulenberg J. Recent increases in symptoms of depressive affect among US adolescents: trends from 1991-2018. Social Psychiatry and Psychiatric Epidemiology: March 2019.
•	Hamilton A, Jang J, Patrick M, Schulenberg J, Keyes KM. Age, period, and cohort effects in frequent marijuana use among US students: 1991-2018. Addiction: May 2019.

### Submitted for Peer Review
•	Keyes KM, Hamilton A, Swanson J, Tracy M, Cerdá M. Simulating the suicide prevention effects of firearms restrictions based on psychiatric hospitalization and treatment records: Social benefits and unintended adverse consequences 
•	Keyes KM, Hamilton A, Patrick M., Schulenberg J. Diverging trends and the relationship between binge drinking and depressive symptoms among adolescents in the US from 1991 through 2018
•	Cerdá M, Mauro C, Hamilton A, Chen C, Wall M, Keyes KM, Martins M. Marijuana use and cannabis use disorder following legalization of recreational marijuana use: what happens to adolescents and adults?
•	Blanchard A, Hamilton A, Li G, Dayan P. Trends and Characteristics of Playground Equipment-Related Extremity Fractures in Children Presenting to US Emergency Departments.

### Presentations at National Conferences
•	How could firearm disqualification among those with a history of intimate partner violence affect population and female-specific rates of homicide? An agent-based modeling approach. Society for Epidemiologic Research, June 2018, Baltimore, MD.
•	Age, period, cohort effects of adolescent loneliness, self-derogation and low self-esteem: 1991-2018. Society for Epidemiologic Research, June 2019, Minneapolis, MN.

### Abstracts Presented at National Conferences
•	Hamilton A, Tracy M, Keyes KM, Cerda M. Modeling the population dynamics of incarceration through simulation: Challenges and progress. Society for Epidemiologic Research, June 2017, Seattle, WA.
•	Hamilton A, Tracy M, Keyes KM, Cerda M. Mental health and firearm violence: From evidence to action. Society for Epidemiologic Research, June 2016, Miami, FL.
•	Hamilton A, Tracy M, Keyes KM, Cerda M. Mental health and firearm violence: Innovative use of social networks in an agent based model. Society for Epidemiologic Research, June 2016, Miami, FL.
•	Hamilton A, Keyes KM, Kandel D. Adolescent cigarette smoking as a gateway to cocaine use: epidemiological evidence. Society for Epidemiologic Research, June 2015, Denver, CO.
•	Hamilton A, Ananth CV, Keyes KM, Gissler M, Wu C, Liu S, Williams MA, Skjærven R, Tikkanen M, Cnattingius S. International Comparison of Rates of Placental Abruption: Age-Period-Cohort Analysis. Society for Epidemiologic Research, June 2014, Seattle, WA.
•	Hamilton A, Roguski K, Lipcsey-Magyar, Roe-Dale R, Frederick KA. Residual Analysis in Modeling Real-Time Changes of Electroosmotic Flow. Joint Mathematics Meeting, January 2011, New Orleans, LA.

